### ISSUE TITLE
Grafana Upgrade and Configuration Issues with the Geomap Panel After Version 9.2.10"

### ISSUE THREAD

**Issue by Rukasu1609** [Bsmith101/OPNsense-Dashboard#80]
Following the guide, I successfully implemented all the steps, and everything worked as expected. Currently, I am working on adjusting the docker-compose.yml file to update the programs to a more recent version.

Overview of the changes:

InfluxDB: 2.6.1 → 2.7.11
Elasticsearch-oss: 7.10.2 → OpenSearch 2.18.0
Graylog: 5.0.2 → 6.1.5
Grafana: 9.2.10 → 11.4.0
MongoDB: 6.0.4 → 7.0.15

Since Elasticsearch-oss is End of Life and no longer supported by Grafana, I decided to switch to OpenSearch, which was originally developed as a fork of Elasticsearch-oss.

In the newer versions of Grafana, the world map panel no longer works. The reason is that the "Worldmap Panel" in Grafana has been replaced by the "Geomap Panel." However, all other panels work without any issues. The older version 9.2.10 of Grafana still runs the world map as expected. 

Here’s an overview of the adjusted dashboard:
<img width="1217" alt="Screenshot 2025-01-12 151418" src="https://github.com/user-attachments/assets/2ffd0097-0d33-4bec-91a7-d4b94ad29704" />

I have provided the configuration snippet from Grafana 9.2.10 using the old "Worldmap Panel," which works as expected:
<img width="1246" alt="Screenshot 2025-01-12 151726" src="https://github.com/user-attachments/assets/a82f4dc1-be88-42fe-b243-7b6b69aa53c2" />

Below is the configuration snippet for the new "Geomap Panel," where it does not function properly:
 
<img width="1246" alt="Screenshot 2025-01-12 151855" src="https://github.com/user-attachments/assets/f657ca3c-8de6-467b-91d8-386830bea823" />
<img width="1247" alt="Screenshot 2025-01-12 151924" src="https://github.com/user-attachments/assets/ec33acdc-9ad1-4d23-8cc5-6ddbccdde58b" />

Now, the question is whether anyone knows how I need to configure it in the new panel type?

**Comment by Skriczer** [comment]
Hey there, seems like we are doing the exact same thing with that config.
The way I managed to fix it is by adding a second data source, since geomap requires a data field with country codes.
All you have to do is query for src-ip-get-country, and you will get your values.
Then simply add them to the filter on the map settings. 

![Screenshot 2025-01-15 195423](https://github.com/user-attachments/assets/f069870d-6ca1-4ee2-a203-0d277b599a09)

**Comment by Rukasu1609** [comment]
Thank you for the quick response! I tried it right away, and it now works perfectly with the latest Grafana version.
During testing, I discovered that the first query in your screenshot (Query A) is unnecessary and can be completely omitted, as it is not needed.

I was initially a bit confused since the values don't exactly match the previous ones. It's important to include the Action: "block" variable in the query. Otherwise, it will also count requests that are not blocked, which skews the statistics.

Since I am based in Germany, this causes a significant deviation in my case. I have a before-and-after screenshot that I'd like to share with you:

![Image](https://github.com/user-attachments/assets/3f9c3c26-f944-48e2-9d79-5a171be9dd41)

![Image](https://github.com/user-attachments/assets/84b48eb4-b7e1-4ee8-ab4b-5a32571cd9f1)

**Comment by tismofied** [comment]
> Following the guide, I successfully implemented all the steps, and everything worked as expected. Currently, I am working on adjusting the docker-compose.yml file to update the programs to a more recent version.



You mind sharing your compose file please?

**Comment by neuling10** [comment]
I would also be very happy if you could share the compose file :D

I am currently working on a Macvlan extension

**Comment by Rukasu1609** [comment]
Sure, I can share the Docker-Compose file with you. In the file, I’ve set the latest version (latest) for Grafana and InfluxDB so that the most current version can always be tested. However, you can change this to a specific release version at any time.

To share the file with you, I’ve reset some settings to their default values:

- The Graylog login has been reset. The username is admin, and the password is also admin. These credentials should definitely be changed.
- The timezone needs to be manually adjusted to fit your environment.
- The Grafana login has also been reset to the default values. The username is opnsense, and the password is opnsense. These credentials should also be changed.

From my own experience, I can offer a few important tips, as I ran into some issues myself:

- The virtual machine should have at least 64 GB of disk space. With less storage, it quickly filled up for me, causing Graylog to crash and not restart
- If you’re using Proxmox as a hypervisor, make sure the CPU configuration for the VM is set to the "host" type. Otherwise, I encountered issues with OpenSearch and Graylog, which were resolved after making this adjustment.

I’m also including the customized Grafana dashboard version. Important: Insert OpenSearch instead of Elasticsearch as the data source in Grafana. I’ve added my two VPN interfaces to the dashboard, so the data is directly visualized. If you don’t want that, simply adjust or remove them.
<img width="1085" alt="Image" src="https://github.com/user-attachments/assets/587b3f20-e221-44a1-b4d4-f4258e277f34" />

My Docker-Compose and Grafana File:
[Files.zip](https://github.com/user-attachments/files/18631581/Files.zip)

Additionally, I’d like to integrate Unbound DNS and Zenarmor in the same dashboard. Has anyone already done this?

**Comment by neuling10** [comment]
Thank you very much @Rukasu1609 

Unfortunately I have a problem with the map. The map doesn't show any data. Do you have any other changes in your config regarding the configured.md from bsmithio?

Maybe there is a problem in my Opensearch Grafana data source. My configuration:
![Image](https://github.com/user-attachments/assets/cebf847d-c152-47a8-9e96-46a108d9fac9)

I think the "opensearch" in the docker compose file has to be replaced with the graylog host IP adress, right?
`    environment:
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200`

**Comment by Rukasu1609** [comment]
Hello,

You don't need to change the IP address in the Docker Compose file. What's important is that you use the same address in the Grafana configuration. For example, if the Docker file contains environment: - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200, your configuration should look like this:

![Image](https://github.com/user-attachments/assets/12e3e398-9911-44c1-951a-82d1f7bc3782)

If it still doesn't work, we need to keep investigating the cause.

There are also other panels in Grafana that access OpenSearch. Are you seeing any data there?

Have you checked if all containers are running using the command sudo docker ps?

Did you import my modified Grafana file and select the correct data source in the dashboard?

Did you follow the steps in the "Configuring Graylog" guide? Have you registered with Maxmind, generated the license key, and applied it in Graylog?

If problems persist, we can work together to find a solution. Just let me know.

**Comment by neuling10** [comment]
Many thanks @Rukasu1609. My dashboard is working now - the dashboard looks amazing 🥇 

The error was the missing Graylog database. I had to use this download command:
`wget -O GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=MAXMIND_KEY&suffix=tar.gz" \
&& tar -xzvf GeoLite2-Country.tar.gz \
&& mv GeoLite2-Country_*/GeoLite2-Country.mmdb /usr/share/graylog/data/data/` 

Just one more question to the Grafana dashboard:
Is it possible to use the interface' "friendlyname" as row title instead of the interface name?
 
![Image](https://github.com/user-attachments/assets/c1bc3328-9e90-454e-bc3b-6ded56f2f00b)

**Comment by Rukasu1609** [comment]
I'm glad to hear that things are working for you now. Regarding your question, you can adjust the Row Title by going to the Edit mode at the top right of the dashboard, then clicking on the gear icon of the respective row. 
![Image](https://github.com/user-attachments/assets/d145b7f2-b7ed-44fe-964a-70bb6fb97b44)

Normally, there is a placeholder for the interface, but I'm not sure how to display the friendly name using a placeholder. However, you can simply write the desired friendly name yourself.
<img width="280" alt="Image" src="https://github.com/user-attachments/assets/33eaae19-91f3-4d8f-95a0-fe31c51b4bb4" />

**Comment by neuling10** [comment]
Thank you, I have tested it. Unfortunately, all LAN interface tables have the same name now

![Image](https://github.com/user-attachments/assets/3400a106-4e5d-4d13-ae5f-1465214f398a)

I have tested the title "LAN - $friendlyname" but it doesn't work. 

Another idea would be to create a sepaate table for each interface. But that would be an enormous effort...

**Comment by tismofied** [comment]
Thank you @Rukasu1609 for the detailed steps. Got everything working with latest containers.
anyone have an idea how to remove these drop down menus at the very top . such a waste of space for kiosk mode.
I even tried kiosk mode and they are still there.

![Image](https://github.com/user-attachments/assets/3e5251c8-e7ff-4096-ba4b-1dcec9abdc4d)

**Comment by tismofied** [comment]
@Rukasu1609 sorry for the ping. I am using your files, I am hoping you have some insights what could be wrong
<details>
<summary> : This is my compose file </summary>
```

services:
  mongodb:
    container_name: mongo
    image: mongo:7.0.15
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - TZ=EST
    networks:
      - graylog
  opensearch:
    container_name: opnsense-opensearch
    image: opensearchproject/opensearch:2.18.0
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    # - plugins.security.disabled=true
    ports:
      - 9200:9200
      - 9600:9600
    restart: unless-stopped
    networks:
      - graylog
  graylog:
    container_name: opnsense-graylog
    image: graylog/graylog:6.1.7
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - TZ=EST
      - ROOT_TIMEZONE=EST
      - GRAYLOG_TIMEZONE=EST
      - GRAYLOG_PASSWORD_SECRET=redacted
      - GRAYLOG_ROOT_PASSWORD_SHA2=redacted
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    depends_on:
      - mongodb
      - opensearch
    ports:
      - 9000:9000
      - 1514:1514/udp
      # Syslog TCP Optional
      #- 1514:1514
    restart: unless-stopped
  influxdb:
    container_name: opnsense-influxdb
    image: influxdb:latest
    ports:
      - 8487:8086
    volumes:
      - influxdb2_data:/var/lib/influxdb2
    environment:
      - TZ=EST
    restart: unless-stopped
    networks:
      - graylog
  grafana:
    container_name: opnsense-grafana
    image: grafana/grafana:latest
    ports:
      - 3350:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - TZ=EST
      - GF_SECURITY_ADMIN_USER=opnsense
      - GF_SECURITY_ADMIN_PASSWORD=redacted
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: unless-stopped
    networks:
      - graylog
networks:
  graylog:
    driver: bridge
volumes:
  grafana_data: 
  influxdb2_data: 
  graylog_data: 
  es_data: 
  mongodb_data: 
  opensearch_data: 

```

</details>
